### ISSUE TITLE
are you sure GL can be sane

### ISSUE THREAD

**Issue by RdrSeraphim** [charles-l/sanegl#1]
i mean, after all, it is GL

**Comment by charles-l** [comment]
i sure hope so...
- if there's less boilerplate, i won't rip my hair out
- if i don't have to mess with global state, i won't have insane debugging sessions
- NoMoreFreakingCamelCase snake_case_ftw_amirite?

**Comment by RdrSeraphim** [comment]
I mean, I like camel case (personally). But hey, if this makes OpenGL quite manageable and less... _annoying_, I can't wait to see what comes of this.
